config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    #omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :tasks, only: [:index, :new, :show, :create, :update, :destroy]
  get 'home/index'
  root 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            <%= image_tag image_url("Redo-32.png") %>
            Redo
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <% if user_signed_in? %>
            <%= form_with url: tasks_path, method: :get, id: "search-form" do |f| %>
              <%= f.text_field :search, class: "mr-sm-2" %>
              <%= f.submit "Search", class: "btn btn-outline-success my-2 my-sm-m0" %>
            <% end %>
          <% end %>
          <div class="flex-row ml-md-auto d-none d-md-flex">
            <% if user_signed_in? %>
              <%= form_for :user, html: {class: "form-inline"}, url: destroy_session_path(:user), method: :delete do |f| %>
                <%= f.submit "Sign out", class: "btn btn-primary" %>
              <% end %>
            <% else %>
              <%= link_to "Sign in", new_session_path(:user), {class: "btn btn-primary pull-right"} %>
            <% end %>
          </div>
        </div>
      </nav>
    </header>
    <div class="container mt-6">
      <%= yield %>
    </div>
  </body>
</html>